/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibrarySessionIdRouteImport } from './routes/library.$sessionId'
import { Route as LiteratureIndexRouteImport } from './routes/literature.index'
import { Route as LiteratureLiteratureIdRouteImport } from './routes/literature.$literatureId'
import { Route as LiteratureUploadRouteImport } from './routes/literature.upload'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibrarySessionIdRoute = LibrarySessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => LibraryRoute,
} as any)
const LiteratureIndexRoute = LiteratureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiteratureRoute,
} as any)
const LiteratureLiteratureIdRoute = LiteratureLiteratureIdRouteImport.update({
  id: '/$literatureId',
  path: '/$literatureId',
  getParentRoute: () => LiteratureRoute,
} as any)
const LiteratureUploadRoute = LiteratureUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LiteratureRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/literature': typeof LiteratureRouteWithChildren
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/library/$sessionId': typeof LibrarySessionIdRoute
  '/literature/$literatureId': typeof LiteratureLiteratureIdRoute
  '/literature/upload': typeof LiteratureUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/library/': typeof LibraryIndexRoute
  '/literature/': typeof LiteratureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/library/$sessionId': typeof LibrarySessionIdRoute
  '/literature/$literatureId': typeof LiteratureLiteratureIdRoute
  '/literature/upload': typeof LiteratureUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/library': typeof LibraryIndexRoute
  '/literature': typeof LiteratureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/literature': typeof LiteratureRouteWithChildren
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/library/$sessionId': typeof LibrarySessionIdRoute
  '/literature/$literatureId': typeof LiteratureLiteratureIdRoute
  '/literature/upload': typeof LiteratureUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/library/': typeof LibraryIndexRoute
  '/literature/': typeof LiteratureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/literature'
    | '/settings'
    | '/upload'
    | '/library/$sessionId'
    | '/literature/$literatureId'
    | '/literature/upload'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/library/'
    | '/literature/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/upload'
    | '/library/$sessionId'
    | '/literature/$literatureId'
    | '/literature/upload'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/library'
    | '/literature'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/literature'
    | '/settings'
    | '/upload'
    | '/library/$sessionId'
    | '/literature/$literatureId'
    | '/literature/upload'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/library/'
    | '/literature/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LiteratureRoute: typeof LiteratureRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$sessionId': {
      id: '/library/$sessionId'
      path: '/$sessionId'
      fullPath: '/library/$sessionId'
      preLoaderRoute: typeof LibrarySessionIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/literature/': {
      id: '/literature/'
      path: '/'
      fullPath: '/literature/'
      preLoaderRoute: typeof LiteratureIndexRouteImport
      parentRoute: typeof LiteratureRoute
    }
    '/literature/$literatureId': {
      id: '/literature/$literatureId'
      path: '/$literatureId'
      fullPath: '/literature/$literatureId'
      preLoaderRoute: typeof LiteratureLiteratureIdRouteImport
      parentRoute: typeof LiteratureRoute
    }
    '/literature/upload': {
      id: '/literature/upload'
      path: '/upload'
      fullPath: '/literature/upload'
      preLoaderRoute: typeof LiteratureUploadRouteImport
      parentRoute: typeof LiteratureRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibrarySessionIdRoute: typeof LibrarySessionIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibrarySessionIdRoute: LibrarySessionIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface LiteratureRouteChildren {
  LiteratureLiteratureIdRoute: typeof LiteratureLiteratureIdRoute
  LiteratureUploadRoute: typeof LiteratureUploadRoute
  LiteratureIndexRoute: typeof LiteratureIndexRoute
}

const LiteratureRouteChildren: LiteratureRouteChildren = {
  LiteratureLiteratureIdRoute: LiteratureLiteratureIdRoute,
  LiteratureUploadRoute: LiteratureUploadRoute,
  LiteratureIndexRoute: LiteratureIndexRoute,
}

const LiteratureRouteWithChildren = LiteratureRoute._addFileChildren(
  LiteratureRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LiteratureRoute: LiteratureRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
